apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
spec:
  ports:
  - name: "80"
    nodePort: 31990
    port: 80
    protocol: TCP
  selector:
    app: nginx
  type: NodePort