apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myinvest
    tier: backend
  name: backend
spec:
  ports:
  - name: "3000"
    protocol: TCP
    port: 3000
    nodePort: 32001
  type: NodePort
  selector:
    app: myinvest
    tier: backend
status:
  loadBalancer: {}
