apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secrettest
    tier: mysql
  name: mysqlsecret
spec:
  replicas: 1
  selector:
      matchLabels:
        app: secrettest
        tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: secrettest
        tier: mysql
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dbconfig
              key: db_name
        - name: MYSQL_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: rootpw
        - name: MYSQL_USER
          valueFrom: 
            secretKeyRef:
              name: dbsecret
              key: username
        image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
      restartPolicy: Always
